#!/bin/bash

LIBS=$(find jre/ -type f -exec file {} \; | grep ELF | awk -F ":" '{print $1}')

function copy_deps() {
	DEPS=$(ldd $1 2> /dev/null | grep "=>" | grep -v not | awk '{print $3}' | grep -v $USER) 
	for I in ${DEPS[@]} 
	do 
		DIR=$(dirname $I) 
		FNAME=$(basename $I) 
	
		mkdir -p stage1/$DIR/ 2> /dev/null
		cp $I stage1/$DIR/
	done
}

function add() {
	DIR=$(dirname $1) 
	FNAME=$(basename $1) 
	mkdir -p stage1/$DIR  
	if [ -z $2 ] ; then 
		cp $1 stage1/$DIR/$FNAME 
	else
		cp $1 stage1/$2
	fi
	copy_deps $1
}

for I in ${LIBS[@]} 
do
	copy_deps $I
done

mkdir -p stage1/lib64 stage1/usr/lib/x86_64-linux-gnu/ 2> /dev/null

cp stage1/jre/lib/libjli.so stage1/lib/ 

add /lib/ld-linux-aarch64.so.1
add /usr/lib/aarch64-linux-gnu/libutil.so.1
add /usr/bin/stty 
add /usr/bin/tty 
add /usr/bin/infocmp 
add /usr/lib/terminfo/x/xterm-256color 
add /lib/terminfo/l/linux 
add /lib/aarch64-linux-gnu/libstdc++.so.6 
add /lib/aarch64-linux-gnu/libgcc_s.so.1 
add /lib/aarch64-linux-gnu/libm.so.6 
add /lib/aarch64-linux-gnu/libc.so.6 
# add /usr/sbin/v86d /sbin/
